# Generated by Django 3.2 on 2022-12-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapp', '0003_app_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='docker_container_internal_id',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
