# Generated by Django 4.0.4 on 2022-12-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapp', '0004_container_docker_container_internal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
