# Generated by Django 4.0.4 on 2022-12-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapp', '0006_remove_container_docker_container_internal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='envs',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='container',
            name='status',
            field=models.CharField(choices=[('Running', 'Running'), ('Running', 'Finished'), ('Error', 'Error')], default='Running', max_length=20),
        ),
    ]
